Rails.application.routes.draw do
  root 'login#index'
  get 'login' => 'login#index'
  get 'register' => 'login#register'
  get ':id/edit' => 'login#edit'
  post ':id/update' => 'login#update'
  post 'create' => 'login#create'
  get 'events' => 'events#index'
  get 'events/new' => 'events#new'
  post 'events/search' => 'events#search'
  post 'events/create' => 'events#create'
  get 'events/past' => 'events#past'
  get 'events/:id' => 'events#show'
  get 'events/:id/join' => 'events#join'
  get 'events/:id/edit' => 'events#edit'
  post 'events/:id/update' => 'events#update'
  delete 'events/:id/destroy' => 'events#destroy'
  delete 'logout' => 'login#destroy'
end
